# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b09d3fc7d51f78524635acf9e0f28079b794524d2f07635d4bd23f441f62c24deab9bbea0ac96aa91f0417bebe6898afc2e2d95deb10fd4c6941e38ac9d0b5

test:
  secret_key_base: 5b8f0a250bde38dec16d2db8f6416f5a7f74270355025abf8175442d48a6daaa4db8a7f9d656ba21b0840b581e1c94abd996ec4b92327cb54d620a87537e57d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
